name: Build Dev

on:
  push:
    branches: [ "dev" ]
    paths:
    - .github/workflows/build-dev.yml
    - AudioLink/**
    - AudioLink.sln

jobs:
  build:
    name: Build
    strategy:
      matrix:
        game-version: [ 1.29.1, 1.34.2, 1.37.1, 1.40.8, 1.42.1 ]
    uses: Aeroluna/workflows/.github/workflows/bs-build-version-release.yml@main
    with:
      project-path: AudioLink/AudioLink.csproj
      game-version: ${{ matrix.game-version }}
    secrets: inherit
