name: Upload

on:
  workflow_dispatch:

jobs:
  upload:
    name: Upload
    uses: Aeroluna/workflows/.github/workflows/bs-upload-release-to-beatmods.yml@main
    with:
      mods: '{"AudioLink": 261}'
    secrets:
      token: ${{ secrets.PAT }}
